language: rust
rust:
  - 1.32.0

env:
  - ARCH=x86_64 FEATURES=''
  - ARCH=i686 FEATURES=''
  - ARCH=x86_64 FEATURES='serde1'
  - ARCH=i686 FEATURES='serde1'

matrix:
  include:
    - rust: nightly
      os: linux
      name: "Minimal dependency versions"
      script:
        - cargo generate-lockfile -Z minimal-versions
        # Building the test results in problems with rand 0.6
        - cargo check --features serde1

addons:
  apt:
    packages:
      - gcc-multilib

script:
  - cargo build --verbose --features "$FEATURES"
  - cargo test --verbose --features "$FEATURES"
