[package]
authors = ["Vinzent Steinberg <Vinzent.Steinberg@gmail.com>"]
categories = ["science", "no-std"]
description = "Calculate statistics iteratively"
documentation = "https://docs.rs/average"
keywords = ["stats", "mean", "skewness", "kurtosis", "quantile"]
license = "MIT/Apache-2.0"
name = "average"
readme = "README.md"
repository = "https://github.com/vks/average"
version = "0.12.0"
edition = "2018"
include = ["src/**/*", "benches/*", "LICENSE-*", "README.md"]

[features]
serde1 = ["serde", "serde_derive", "serde-big-array"]
nightly = []
std = ["easy-cast/std", "num-traits/std"]
libm = ["easy-cast/libm", "num-traits/libm"]
default = ["libm"]

[[bench]]
harness = false
name = "mean"

[[bench]]
harness = false
name = "min"

[[bench]]
harness = false
name = "kurtosis"

[dependencies]
num-traits = { version = "0.2", default-features = false }
float-ord = "0.3"
easy-cast = { version = "0.4", default-features = false, optional = true }
serde = { version = "1", features = ["derive"], optional = true }
serde_derive = { version = "1", optional = true }
serde-big-array = { version = "0.3.0", optional = true }
rayon = { version = "1.3", optional = true }

[dev-dependencies]
bencher = "0.1"
rand = "0.8"
rand_xoshiro = "0.6"
rand_distr = "0.4"
serde_json = "1"
streaming-stats = "0.2"
quantiles = "0.7"
proptest = "0.10"
# byteorder is not a direct dependency, but the MSRV of 1.4 is higher than ours.
# Therefore, we have to enforce version 1.3.
byteorder = "=1.3"

[package.metadata.docs.rs]
# Enable certain features when building docs for docs.rs
features = ["libm", "serde1", "rayon"]
